version: '3'
services:
  # web:
  #   image: openjdk:11
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/project
  #     - .m2:/root/.m2
  #   working_dir: /project
  #   entrypoint: ./mvnw spring-boot:run
  #   depends_on:
  #     - db
  db:
    image: mysql
    volumes:
      - ./db:/scripts
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  tomcat:
    build:
      context: .
      dockerfile: docker/tomcat/Dockerfile
    volumes:
      - ./target:/usr/local/tomcat/work
  apache:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    ports:
      - "8080:80"
